spring:
   application:
      name: tax-tracker
   datasource:
      url: ljs-project2-db-instance.cx4dqztdn4yr.us-east-1.rds.amazonaws.com/taxtracker
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: none
         
server:
   port: 8080
   
base-url: localhost:8080/

spring.security.user:
   name: admin
   password: admin123