pipeline {
    agent any

    stages {
        stage ('AWS LCI') {
            agent {
                docker{
                    image 'amazon/aws-cli'
                    args "--entrypoint=''"
                }
            }
            steps {
                sh 'aws --version'
            }
        }
    }
}